# .github/workflows/build.yml
name: Build and Test

on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'
  pull_request:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies with Poetry
        run: |
          pip install poetry
          poetry install
          eval $(poetry env activate)
          poetry run python --version

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

  test:
    needs: build  # Ensures tests run only after a successful build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Restore Poetry virtualenv cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies with Poetry
        run: |
          pip install poetry
          poetry install
          eval $(poetry env activate)
          poetry run python --version

      - name: Run tests
        run: |
          eval $(poetry env activate)
          pytest tests/