# .github/workflows/build.yml
name: Build and Test

on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'
  pull_request:
    branches:
      - main
      - 'feature-*'
      - 'bugfix-*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Run tests
        run: poetry run python -m pytest tests/
